<?php

/*
	TODO: Implement a class for basic REST signature.

	Signature is generated by the following algorithm:

		- Add timestamp, random nounce and public api key to the request parameters, wether these are GET or POST-style parameters doesnt matter.

		- Combine HTTP method, URL to the REST call, GET/POST/REQUEST parameters ordered alphabetically by name first then
		colliding parameters by value. These sections are urlencoded and then combined with '&' character.

		- Generate HMAC hash from this combination as data, secret api key as the key.

		- Add Authorization field to HTTP header with base64-encoded HMAC hash above as the value (signature)

	So we need to 

		- Generate the signature from the client call
		- Generate the signature from the servers receivement
		- Fetch the signature from headers
		- Compare the signatures
*/